# =============================================================================
# Figure 3 — "The appraisal space"
# PCA/circumplex biplot: 8 rating adjectives as loading vectors, 16 clips at
# measured (comfort, richness), coloured/shaped by intended quadrant, with an
# arrow per clip from its measured position to the INTENDED position:
# the intended angle (45/135/225/315 deg) at the CLIP'S OWN radius.
# (Choice stated: angular displacement only; radius is not re-targeted.)
# Source: output/analysis_02_appraisal_structure/ (regenerated by
# code/mod02_appraisal_structure.R).
# Single panel, 85 mm single column (circumplex needs 1:1 aspect; moderate
# density: 16 points + 16 arrows + 8 vectors reads fine at 85 mm).
# =============================================================================

source("code/style.R")
library(dplyr); library(readr); library(tidyr); library(tibble)

A02 <- file.path(PROJ, "output/analysis_02_appraisal_structure")
adj  <- read_csv(file.path(A02, "adjective_loadings.csv"), show_col_types = FALSE)
clip <- read_csv(file.path(A02, "clip_geometry.csv"),      show_col_types = FALSE)
quad <- read_csv(file.path(A02, "quadrant_geometry.csv"),  show_col_types = FALSE)

# Quadrant colour/shape mapping (fixed for this figure; distinct from the ROI
# mapping used in Figs 4-6/S1: sky blue / orange / bluish green / reddish purple)
quad_cols   <- c(Q1 = "#56B4E9", Q2 = "#E69F00", Q3 = "#009E73", Q4 = "#CC79A7")
quad_shapes <- c(Q1 = 16, Q2 = 17, Q3 = 15, Q4 = 18)

# Measured quadrant-centroid angle error (deg), shown inside the legend labels
quad <- quad %>% mutate(intended_angle = c(Q1 = 45, Q2 = 135, Q3 = 225, Q4 = 315)[quadrant],
                        err = round(angle_deg - intended_angle))
err_lab <- setNames(paste0(c("Q1", "Q2", "Q3", "Q4"), " (",
                           ifelse(quad$err > 0, "+", ""), quad$err, "°)"),
                    c("Q1", "Q2", "Q3", "Q4"))

# Arrow endpoints: intended angle at the clip's own radius
deg2rad <- function(d) d * pi / 180
clip <- clip %>%
  mutate(x_end = radius * cos(deg2rad(intended_angle)),
         y_end = radius * sin(deg2rad(intended_angle)),
         quadrant = factor(quadrant, levels = c("Q1", "Q2", "Q3", "Q4")))

# Adjective loading vectors + labels just beyond the tips
adj <- adj %>%
  mutate(x_lab = r_comfort * 1.15, y_lab = r_richness * 1.15)

# Unit circle (reference for the correlation vectors)
circ <- tibble(theta = seq(0, 2 * pi, length.out = 361),
               x = cos(theta), y = sin(theta))

lim <- 1.22

p <- ggplot() +
  # intentional reference lines only: origin crosshair + unit circle
  geom_hline(yintercept = 0, colour = "grey75", linewidth = 0.4) +
  geom_vline(xintercept = 0, colour = "grey75", linewidth = 0.4) +
  geom_path(data = circ, aes(x, y), colour = "grey60", linewidth = 0.4,
            linetype = "dashed") +
  # adjective loading vectors
  geom_segment(data = adj, aes(x = 0, y = 0, xend = r_comfort, yend = r_richness),
               colour = "grey30", linewidth = 0.55,
               arrow = arrow(length = unit(0.16, "cm"), type = "closed")) +
  geom_text(data = adj, aes(x_lab, y_lab, label = item),
            size = 8 / .pt, colour = "grey20", family = "Helvetica") +
  # clips: measured position, arrow toward intended-angle position
  geom_segment(data = clip,
               aes(x = comfort, y = richness, xend = x_end, yend = y_end,
                   colour = quadrant),
               linewidth = 0.45, lineend = "round",
               arrow = arrow(length = unit(0.12, "cm"), type = "open"),
               show.legend = FALSE) +
  geom_point(data = clip,
             aes(comfort, richness, colour = quadrant, shape = quadrant),
             size = 2.4, stroke = 0.7) +
  scale_colour_manual(values = quad_cols, labels = err_lab, name = NULL) +
  scale_shape_manual(values = quad_shapes, labels = err_lab, name = NULL) +
  scale_x_continuous(breaks = c(-1, -0.5, 0, 0.5, 1), limits = c(-lim, lim)) +
  scale_y_continuous(breaks = c(-1, -0.5, 0, 0.5, 1), limits = c(-lim, lim)) +
  coord_fixed() +
  labs(x = "Comfort (z)", y = "Richness (z)") +
  theme_pub() +
  theme(legend.position.inside = c(0.99, 0.99),
        legend.justification = c(1, 1),
        legend.text = element_text(size = 8),
        legend.key.height = unit(0.32, "cm"),
        legend.spacing.y = unit(0.02, "cm"))

save_fig(p, file.path(FIGDIR, "fig3_appraisal_space.png"), 85, 85)

# ---- data lock: exactly the plotted values ---------------------------------
lock <- bind_rows(
  adj %>% transmute(layer = "adjective_vector", id = item,
                    x = 0, y = 0, xend = r_comfort, yend = r_richness,
                    label = item, quadrant = NA_character_),
  clip %>% transmute(layer = "clip_point", id = clip_id,
                     x = comfort, y = richness, xend = NA_real_, yend = NA_real_,
                     label = NA_character_, quadrant = as.character(quadrant)),
  clip %>% transmute(layer = "intended_arrow", id = clip_id,
                     x = comfort, y = richness, xend = x_end, yend = y_end,
                     label = NA_character_, quadrant = as.character(quadrant))
)
write_csv(lock, file.path(LOCKDIR, "fig3a_appraisal_space.csv"))
cat("fig3 done. Quadrant centroid angle errors (deg):",
    paste(quad$err, collapse = ", "), "\n")
